### ISSUE TITLE
mm2_install.sh script error

### ISSUE THREAD

**Issue by novakmi85** [pavelkonir/czadsb-scripts#1]
Link http://ftp.nl.debian.org/debian/pool/main/o/openssl/libssl1.0.0_1.0.2l-1~bpo8+1_armhf.deb is 404.

Use: http://freedom.dicea.unifi.it/debian/pool/main/o/openssl/libssl1.0.0_1.0.2l-1~bpo8+1_armhf.deb

**Comment by pavelkonir** [comment]
Thank you.

Fixed
